# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlcoordconverterDialog
                                 A QGIS plugin
 Plugin converts between geographical coordinates and two selected polish coordinate systems
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-10-03
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Emil Kielar
        email                : kielaremil@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import QgsGeometry, QgsPoint, QgsCoordinateReferenceSystem, QgsCoordinateTransform, QgsProject, QgsVectorLayer, QgsFeature, QgsField, QgsPointXY
from qgis.PyQt.QtCore import QVariant

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'pl_coordinate_converter_dialog_base.ui'))


class PlcoordconverterDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PlcoordconverterDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
#  lines of code below automatically changes while they are written data in QDoubleSpinBox spbLatDD using latDMStoDD method
        self.spbLatD.valueChanged.connect(self.latDMStoDD)
        self.spbLatM.valueChanged.connect(self.latDMStoDD)
        self.dbspLatS.valueChanged.connect(self.latDMStoDD)
#         check if hemisphere needs to be changed
        self.cmbLatH.currentTextChanged.connect(self.latDMStoDD)

# make the same thing for longitude
        self.spbLngD.valueChanged.connect(self.lngDMStoDD)
        self.spbLngM.valueChanged.connect(self.lngDMStoDD)
        self.dbspLngS.valueChanged.connect(self.lngDMStoDD)
        self.cmbLngH.currentTextChanged.connect(self.lngDMStoDD)
    
# decimal data won't change untill editing in related boxes will be changed
        self.spbLatDD.editingFinished.connect(self.latDDtoDMS)
        self.spbLngDD.editingFinished.connect(self.lngDDtoDMS)
#TODO check connections, either remove unnescesary, or add missing connections
# setting coordinates from geographical to polish specific
        self.spbLatDD.editingFinished.connect(self.ddToCrs_1)
        self.spbLngDD.editingFinished.connect(self.ddToCrs_1)
        self.spbLatD.valueChanged.connect(self.ddToCrs_1)
        self.spbLatM.valueChanged.connect(self.ddToCrs_1)
        self.dbspLatS.valueChanged.connect(self.ddToCrs_1)
        self.spbLngD.valueChanged.connect(self.ddToCrs_1)
        self.spbLngM.valueChanged.connect(self.ddToCrs_1)
        self.dbspLngS.valueChanged.connect(self.ddToCrs_1)

        self.dbspYCoord.valueChanged.connect(self.ddToCrs_2)
        self.dbspXCoord.valueChanged.connect(self.ddToCrs_2)

# decimal data in DM won't change untill editing in related boxes will be changed
        self.spbLatD.valueChanged.connect(self.latDDtoDM)
        self.spbLatM.valueChanged.connect(self.latDDtoDM)
        self.dbspLatS.valueChanged.connect(self.latDDtoDM)
        self.spbLatDD.editingFinished.connect(self.latDDtoDM)

        self.spbLngD.valueChanged.connect(self.lngDDtoDM)
        self.spbLngM.valueChanged.connect(self.lngDDtoDM)
        self.dbspLngS.valueChanged.connect(self.lngDDtoDM)
        self.spbLngDD.editingFinished.connect(self.lngDDtoDM)

# button for adding points from coordinates
        self.addTmpPoint.clicked.connect(self.addTempPtLyr)

        self.cmbPLCrs1.currentTextChanged.connect(self.ddToCrs_1)
        self.cmbPLCrs1.currentTextChanged.connect(self.ddToCrs_1)

        self.cmbPLCrs2.currentTextChanged.connect(self.ddToCrs_2)
        self.cmbPLCrs2.currentTextChanged.connect(self.ddToCrs_2)
    
    def latDMStoDD(self):
        iDeg = self.spbLatD.value()
        iMin = self.spbLatM.value()
        iSec = self.dbspLatS.value()
        sHem = self.cmbLatH.currentText()
        
        dDD = float(iDeg) + iMin / 60 + iSec / 3600
        if sHem == "S":
            dDD = dDD * -1
        
        self.spbLatDD.setValue(dDD)
        
    def lngDMStoDD(self):
        iDeg = self.spbLngD.value()
        iMin = self.spbLngM.value()
        iSec = self.dbspLngS.value()
        sHem = self.cmbLngH.currentText()
        
        dDD = float(iDeg) + iMin / 60 + iSec / 3600
        if sHem == "W":
            dDD = dDD * -1
        
        self.spbLngDD.setValue(dDD)
    
    def latDDtoDM(self):
        iDeg = self.spbLatD.value()
        iMin = self.spbLatM.value()
        iSec = self.dbspLatS.value()

        dM = iMin + iSec / 60

        self.spbLatDM_D.setValue(iDeg)
        self.spbLatDM_M.setValue(dM)

    def lngDDtoDM(self):
        iDeg = self.spbLngD.value()
        iMin = self.spbLngM.value()
        iSec = self.dbspLngS.value()

        dM = iMin + iSec / 60

        self.spbLngDM_D.setValue(iDeg)
        self.spbLngDM_M.setValue(dM)

    def latDDtoDMS(self):
        dDD = self.spbLatDD.value()
        
        # get only degrees, by creating int from it
        iDeg = int(dDD)
        dMin = (dDD - iDeg) * 60
        iMin = int(dMin)
        dSec = (dMin - iMin) * 60
        
        self.spbLatD.setValue(abs(iDeg))
        self.spbLatM.setValue(abs(iMin))
        self.dbspLatS.setValue(abs(dSec))
        
        if dDD < 0:
            self.cmbLatH.setCurrentText("S")
        else:
            self.cmbLatH.setCurrentText("N")

    def lngDDtoDMS(self):
        dDD = self.spbLngDD.value()
        
        # get only degrees, by creating int from it
        iDeg = int(dDD)
        dMin = (dDD - iDeg) * 60
        iMin = int(dMin)
        dSec = (dMin - iMin) * 60
        
        self.spbLngD.setValue(abs(iDeg))
        self.spbLngM.setValue(abs(iMin))
        self.dbspLngS.setValue(abs(dSec))
        
        if dDD < 0:
            self.cmbLngH.setCurrentText("W")
        else:
            self.cmbLngH.setCurrentText("E")    
    
    # returning proper crs, based on given spatial referrence name
    def setCrs(self, epsg_code):
        epsg = 'EPSG:'
        if epsg_code == 'układ PL-1992':
            epsg += '2180'
        elif epsg_code == 'układ PL-2000 strefa V':
            epsg += '2176'
        elif epsg_code == 'układ PL-2000 strefa VI':
            epsg += '2177'
        elif epsg_code == 'układ PL-2000 strefa VII':
            epsg += '2178'          
        elif epsg_code == 'układ PL-2000 strefa VIII':
            epsg += '2179'   
        return epsg

    # setting coordinates from geographical to polish specific
    #TODO merge functions below into one
    def ddToCrs_1(self):
        geom = QgsGeometry(QgsPoint(self.spbLngDD.value(), self.spbLatDD.value()))
        sourceCrs = QgsCoordinateReferenceSystem('EPSG:4326')
        destCrs = QgsCoordinateReferenceSystem(self.setCrs(self.cmbPLCrs1.currentText()))
        tr = QgsCoordinateTransform(sourceCrs, destCrs, QgsProject.instance()) 
        geom.transform(tr)  
        self.dbspXCoord.setValue(geom.asPoint().y())
        self.dbspYCoord.setValue(geom.asPoint().x())

    def ddToCrs_2(self):
        geom = QgsGeometry(QgsPoint(self.dbspYCoord.value(), self.dbspXCoord.value()))
        sourceCrs = QgsCoordinateReferenceSystem(self.setCrs(self.cmbPLCrs1.currentText()))
        destCrs = QgsCoordinateReferenceSystem(self.setCrs(self.cmbPLCrs2.currentText()))
        tr = QgsCoordinateTransform(sourceCrs, destCrs, QgsProject.instance()) 
        geom.transform(tr)  
        self.dbspXCoord_2.setValue(geom.asPoint().y())
        self.dbspYCoord_2.setValue(geom.asPoint().x())
    
    #adding temporary point layer from coordinates
    def addTempPtLyr(self):
        #adding temp point layer
        vl = QgsVectorLayer("Point", "punkt z kalkulatora współrzędnych", "memory")
        pr = vl.dataProvider()
        pr.addAttributes([QgsField("X", QVariant.Double,'double',2,10)])
        pr.addAttributes([QgsField("Y", QVariant.Double,'double',2,10)])
        vl.updateFields() 
        QgsProject.instance().addMapLayer(vl)

        #adding point to it
        f = QgsFeature()
        f.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(self.spbLngDD.value(), self.spbLatDD.value())))
        f.setAttributes([self.spbLngDD.value(), self.spbLatDD.value()])
        pr.addFeature(f)
        vl.updateExtents() 

